apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    env: development

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    env: development
spec:
  replicas: 1
  template:
    spec:
      #containers:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: crixo/k8s-basic-demo-todo-app:kind
        name: app