apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-basic-demo

resources:
  # https://github.com/kubernetes/kubernetes/issues/68737
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - todo-app-deployment.yaml
  - todo-app-service.yaml