apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    hello: world
    env: base
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      initContainers:
      - name: migration
        image: crixo/k8s-basic-demo-todo-app
        args:
        - --migration-only
        env:
          - name: DB_HOST
            value: "mysql"
      containers:
      - name: app
        image: crixo/k8s-basic-demo-todo-app
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
          - name: DB_HOST
            value: "mysql"